// Shared product data for all pages
export const products = [
  {
    id: 1,
    name: "iPhone 15 Pro",
    price: 999,
    image: "/placeholder.svg?height=300&width=300",
    description: "Latest iPhone with advanced camera system and A17 Pro chip.",
    specifications: ["6.1-inch display", "A17 Pro chip", "128GB storage", "Triple camera system"],
    gallery: [
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
    ],
    category: "Phones",
    brand: "Apple",
  },
  {
    id: 2,
    name: "Samsung Galaxy S24",
    price: 899,
    image: "/placeholder.svg?height=300&width=300",
    description: "Flagship Android phone with AI-powered features.",
    specifications: ["6.2-inch display", "Snapdragon 8 Gen 3", "256GB storage", "Triple camera"],
    gallery: ["/placeholder.svg?height=400&width=400", "/placeholder.svg?height=400&width=400"],
    category: "Phones",
    brand: "Samsung",
  },
  {
    id: 3,
    name: "MacBook Air M3",
    price: 1299,
    image: "/placeholder.svg?height=300&width=300",
    description: "Ultra-thin laptop with M3 chip for incredible performance.",
    specifications: ["13.6-inch display", "M3 chip", "512GB SSD", "18-hour battery"],
    gallery: ["/placeholder.svg?height=400&width=400", "/placeholder.svg?height=400&width=400"],
    category: "Laptops",
    brand: "Apple",
  },
  {
    id: 4,
    name: "Sony WH-1000XM5",
    price: 399,
    image: "/placeholder.svg?height=300&width=300",
    description: "Premium noise-canceling headphones with exceptional sound.",
    specifications: ["30-hour battery", "Active noise canceling", "Quick charge", "Touch controls"],
    gallery: ["/placeholder.svg?height=400&width=400", "/placeholder.svg?height=400&width=400"],
    category: "Accessories",
    brand: "Sony",
  },
  {
    id: 5,
    name: 'iPad Pro 12.9"',
    price: 1099,
    image: "/placeholder.svg?height=300&width=300",
    description: "Professional tablet with M2 chip and Liquid Retina display.",
    specifications: ["12.9-inch display", "M2 chip", "128GB storage", "Apple Pencil support"],
    gallery: ["/placeholder.svg?height=400&width=400", "/placeholder.svg?height=400&width=400"],
    category: "Tablets",
    brand: "Apple",
  },
  {
    id: 6,
    name: "Nintendo Switch OLED",
    price: 349,
    image: "/placeholder.svg?height=300&width=300",
    description: "Gaming console with vibrant OLED screen.",
    specifications: ["7-inch OLED screen", "Enhanced audio", "64GB storage", "Joy-Con controllers"],
    gallery: ["/placeholder.svg?height=400&width=400", "/placeholder.svg?height=400&width=400"],
    category: "Gaming",
    brand: "Nintendo",
  },
]
